import type { SkillDomain } from "./skill.types";

export const skillDomains: readonly SkillDomain[] = [
  {
    slug: "support-utilisateurs",
    title: "Support utilisateurs N1/N2",
    context: "Stage · EDLearn",
    summary:
      "Prendre en charge une demande, établir un diagnostic et accompagner l’utilisateur jusqu’à une résolution ou une escalade documentée.",
    practices: [
      "Qualifier les incidents matériels, système et applicatifs",
      "Résoudre les demandes accessibles et valider la solution avec l’utilisateur",
      "Administrer les comptes et services collaboratifs dans le périmètre confié",
      "Documenter la résolution ou transmettre un historique exploitable",
    ],
    tools: ["Zendesk", "Windows", "macOS", "Google Workspace", "Support à distance"],
    proofs: [
      {
        label: "Support N1/N2 et administration de Google Workspace",
        status: "Mission réalisée",
        source: "E5",
        sourceLabel: "EDLearn",
        href: "/epreuves/e5/support-n1-n2-google-workspace",
      },
      {
        label: "Migration d’un serveur d’impression vers le cloud",
        status: "Mission réalisée",
        source: "E5",
        sourceLabel: "EDLearn",
        href: "/epreuves/e5/migration-serveur-impression-cloud",
      },
    ],
  },
  {
    slug: "gestion-parc",
    title: "Gestion de parc et postes de travail",
    context: "Stage · Secours Catholique",
    summary:
      "Préparer, enrôler et suivre les postes de travail afin de conserver un inventaire fiable et une traçabilité des interventions.",
    practices: [
      "Vérifier le matériel, son affectation et les prérequis du poste",
      "Enrôler les machines et contrôler la remontée d’inventaire",
      "Préparer un poste selon la procédure et les politiques de l’organisation",
      "Mettre à jour les fiches d’équipement et tracer les interventions",
    ],
    tools: ["GLPI", "Windows", "Microsoft Intune", "Windows Autopilot", "Microsoft Entra ID"],
    proofs: [
      {
        label: "Enrôlement des postes et suivi du parc informatique",
        status: "Mission réalisée",
        source: "E5",
        sourceLabel: "Secours Catholique-Caritas France",
        href: "/epreuves/e5/enrolement-postes-suivi-parc",
      },
    ],
  },
  {
    slug: "administration-microsoft",
    title: "Administration Microsoft et services",
    context: "Stage + réalisation E6",
    summary:
      "Administrer les services courants et préparer des environnements Windows structurés, sécurisés et documentés.",
    practices: [
      "Gérer des comptes, groupes et services collaboratifs dans le périmètre confié",
      "Préparer Active Directory, DNS, DHCP, GPO et services de fichiers en laboratoire",
      "Structurer les permissions et les partages avec un modèle de groupes AGDLP",
      "Contrôler les accès et accompagner les migrations de services",
    ],
    tools: [
      "Windows Server 2019–2025",
      "AD DS",
      "GPO",
      "Microsoft Entra ID",
      "Microsoft 365",
      "Azure",
      "DHCP",
      "DNS",
      "DFSN / DFSR",
      "AGDLP",
    ],
    proofs: [
      {
        label: "Migration d’un serveur de fichiers sur site vers le cloud",
        status: "Mission réalisée",
        source: "E5",
        sourceLabel: "Secours Catholique-Caritas France",
        href: "/epreuves/e5/migration-serveur-fichiers-cloud",
      },
      {
        label: "Infrastructure PME et automatisation",
        status: "Réalisation en cours",
        source: "E6",
        sourceLabel: "Dossier technique SISR",
        href: "/epreuves/e6/infrastructure-pme-automatisation",
      },
    ],
  },
  {
    slug: "reseaux-acces-distant",
    title: "Réseaux, Wi-Fi et accès distant",
    context: "Stages + réalisation E6",
    summary:
      "Observer la qualité du réseau, mettre en service des accès distants et préparer une segmentation adaptée aux usages.",
    practices: [
      "Réaliser des relevés et restituer les constats d’un audit Wi-Fi",
      "Déployer, tester et dépanner un accès VPN utilisateur",
      "Préparer des VLAN et des règles de filtrage dans une maquette documentée",
      "Analyser l’adressage, le routage, la traduction d’adresses et la haute disponibilité",
    ],
    tools: [
      "LAN",
      "TCP/IP",
      "Modèle OSI",
      "VLAN",
      "Routage",
      "NAT",
      "HSRP",
      "VPN",
      "Cisco Meraki",
      "Cisco Packet Tracer",
      "OPNsense",
      "pfSense",
    ],
    proofs: [
      {
        label: "Audit du réseau Wi-Fi",
        status: "Mission réalisée",
        source: "E5",
        sourceLabel: "EDLearn",
        href: "/epreuves/e5/audit-reseau-wifi",
      },
      {
        label: "Mise en place et maintenance d’un VPN",
        status: "Mission réalisée",
        source: "E5",
        sourceLabel: "Secours Catholique-Caritas France",
        href: "/epreuves/e5/vpn-acces-distant",
      },
      {
        label: "Segmentation et filtrage de l’infrastructure PME",
        status: "Réalisation en cours",
        source: "E6",
        sourceLabel: "Dossier technique SISR",
        href: "/epreuves/e6/infrastructure-pme-automatisation",
      },
    ],
  },
  {
    slug: "virtualisation-linux",
    title: "Virtualisation et Linux",
    context: "Laboratoires techniques",
    summary:
      "Construire des environnements isolés pour déployer, tester et dépanner des services sans exposer l’infrastructure hôte.",
    practices: [
      "Créer et organiser des machines virtuelles selon le besoin du laboratoire",
      "Administrer des environnements Debian et Ubuntu Server",
      "Conteneuriser un service ou un environnement de développement",
      "Utiliser snapshots, sauvegardes et restauration pendant les phases de test",
    ],
    tools: ["Debian", "Ubuntu Server", "Proxmox", "VMware Fusion Pro", "Docker"],
    proofs: [
      {
        label: "Maquette virtuelle de l’infrastructure PME",
        status: "Réalisation en cours",
        source: "E6",
        sourceLabel: "Dossier technique SISR",
        href: "/epreuves/e6/infrastructure-pme-automatisation",
      },
    ],
  },
  {
    slug: "developpement-automatisation",
    title: "Automatisation et développement web",
    context: "Réalisation E6 + projet personnel",
    summary:
      "Automatiser les opérations répétitives et construire des interfaces web versionnées, déployées et documentées.",
    practices: [
      "Écrire des scripts PowerShell idempotents pour les opérations d’administration",
      "Automatiser des tâches en Bash, Shell et Python",
      "Développer des interfaces accessibles avec React et Next.js",
      "Relier une interface à des données et à des services d’authentification",
      "Versionner le code et organiser son déploiement continu",
    ],
    tools: [
      "PowerShell",
      "Bash / Shell",
      "Python",
      "HTML / CSS",
      "JavaScript / TypeScript",
      "React",
      "Next.js",
      "Tailwind CSS",
      "shadcn/ui",
      "Framer Motion",
      "Node.js",
      "SQL",
      "Prisma",
      "Supabase",
      "Better Auth",
      "Git / GitHub",
      "Vercel",
      "Cloudflare",
      "VS Code",
      "Cursor AI",
    ],
    proofs: [
      {
        label: "Scripts de l’infrastructure PME",
        status: "Réalisation en cours",
        source: "E6",
        sourceLabel: "Dossier technique SISR",
        href: "/epreuves/e6/infrastructure-pme-automatisation",
      },
      {
        label: "Portfolio professionnel multipage",
        status: "Projet en cours",
        source: "Projet",
        sourceLabel: "Projet personnel",
        href: "/projets/portfolio-professionnel",
      },
    ],
  },
];
